### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by sunny**
This PR adds some very basic translation for the texts and placeholder by switching the text on load.

image

Can be tested at: https://share-to-fedi.cults3d.com/?lang=fr

### CODE REVIEW

**Comment by kytta** [comment]
Hi Sunny, thanks for your contribution! At this moment, merging this PR is not foreseeable, as I am working on v3, which changes the whole architecture of S2F, basically. This is also the reason why Netlify and Cloudflare fail (only v3 supports them).

I'll try to merge this in a newer version; you can have a look at it yourself if you checkout the `v3` branch, but I can't promise it won't have breaking changes

**Comment by kytta** [comment]
Btw, love your approach! Reminds me of https://github.com/kytta/vavilon 😁

**Comment by sunny** [comment]
> Btw, love your approach! Reminds me of [kytta/vavilon](https://github.com/kytta/vavilon) 😁

Haha, awesome. I love the addition of `<script data-vavilon-dict="ru"` to hold the other languages! Don’t think this would be necessary here, but it’s a smart way of storing those translations.

> At this moment, merging this PR is not foreseeable, as I am working on v3, which changes the whole architecture of S2F

No worries, I’ll gladly rebuild this onto v3 once you’ve done more progress onto it. Can’t wait for v3 :)

**Comment by kytta** [comment]
Hey Sunny! I have been coding around, and I think I have re-implemented Vavilon in Share2Fedi :D For real, though, I have now come up with a relatively lightweight i18n engine that supports interpolation and translation of attributes. I'd _love_ for it to pre-render it on the server with SSR, but I couldn't get the existing i18n plugins for Astro to work properly (even if I would, they're made for content-heavy websites, which S2F isn't)

Anyway, I have also translated the site into German and Russian. If you want, you can add translations for French and Spanish. Feel free to create a branch from [this commit](https://github.com/kytta/share2fedi/pull/23/commits/b73fb9930f21c895e90b53a0cc750e24120e9959) and to edit [`src/i18n/translations.ts`](https://github.com/kytta/share2fedi/blob/b73fb9930f21c895e90b53a0cc750e24120e9959/src/i18n/translations.ts) (I think the file is pretty straight-forward)

The only thing missing is the translation for the licence and for the privacy policy, as I am importing them from Markdown files. I'll think about how that could be done.

**Comment by kytta** [comment]
Oh, and I'll close this PR for the sake of creating a new one.

**Comment by sunny** [comment]
Awesome! I’ll tackle this when I get some time \o/

Not a big deal, but note that in my translator I went for using only one attribute so that we can update two independent attributes at once. With a `data-translate` and `data-translate-attribute` you couldn’t translate both the title and the inner HTML in this example:

```html
<button title="Share to your Mastodon instance">Toot</button>
```

**Pull request closed without merging**
